#' Create a PG non spatial table from Foreign data wrapper table
#'
#' @param src_tbl coming soon
#' @param dst_tbl coming soon
#' @param pk coming soon
#' @param schema coming soon
#' @param pg_conn_param coming soon
#' @param src_schema coming soon
#' @param flds_to_keep optional
#' @param where
#' @param tbl_comment
#'
#' @return None
#' @export
#'
#' @examples coming soon


fdwTbl2PGnoSpatial <- function(src_tbl, 
                               dst_tbl, 
                               pk,
                               dst_schema, 
                               pg_conn_param, 
                               tbl_comment,
                               src_schema   = 'load', 
                               flds_to_keep = NULL, 
                               where        = '') 
{
  ## if source table has schema appended, strip it off and use src_schema argument
  if (grepl("\\.", src_tbl)) {
    src_tbl <- unlist(strsplit(src_tbl, split = "[.]"))[-1]
  } else {
    src_tbl <- src_tbl
  }

  geom_name <- faibDataManagement::getGeomNamePG(src_schema, src_tbl, pg_conn_param)

  if(where == '' || is.null(where) || is.na(where)) {
    where <- ''
  } else {
    where <- gsub("\'","\'\'", where)
    where <- glue("where {where}")
  }

  if(is.null(flds_to_keep) || flds_to_keep == '' || is.na(flds_to_keep)) {
    ## Keep all attributes
    query = glue("SELECT
                    'SELECT ' || array_to_string(
                                                  ARRAY(
                                                      SELECT
                                                        'o' || '.' || c.column_name
                                                      FROM
                                                        information_schema.columns As c
                                                      WHERE
                                                        table_name = '{src_tbl}'
                                                      AND
                                                        table_schema = '{src_schema}'
                                                      AND
                                                        c.column_name NOT IN ('{geom_name}')
                                                    )
                                      , ',') || '
                 FROM
                  {src_schema}.{src_tbl} AS o {where} ' As sqlstmt")

    sqlstmt <- (faibDataManagement::getTableQueryPG(query, pg_conn_param))$sqlstmt
  } else {
    # Split the original string into elements
    elements <- strsplit(flds_to_keep, ",")[[1]]
    # if objectid is not in requested fields, add it
    if (!("objectid" %in% elements)) {
      elements <- c(elements, "objectid")
    }

    # Add single quotes around each element
    quoted_elements <- paste0("'", elements, "'")

    # Join the quoted elements into a new string
    flds_to_keep <- paste(quoted_elements, collapse = ',')

    query = glue("SELECT
                    'SELECT ' || array_to_string(
                                                  ARRAY(
                                                      SELECT
                                                        'o' || '.' || c.column_name
                                                      FROM
                                                        information_schema.columns As c
                                                      WHERE
                                                        table_name = '{src_tbl}'
                                                      AND
                                                        table_schema = '{src_schema}'
                                                      AND
                                                        c.column_name NOT IN ('{geom_name}')
                                                      AND
                                                        c.column_name IN ({flds_to_keep})
                                                    )
                                      , ',') || '
                 FROM
                  {src_schema}.{src_tbl} AS o {where} ' As sqlstmt")
    sqlstmt <- (faibDataManagement::getTableQueryPG(query, pg_conn_param))$sqlstmt
  }
  today_date <- format(Sys.Date(), "%Y-%m-%d")
  ## Alter the SQL statement to cast the
  faibDataManagement::sendSQLstatement(glue('DROP TABLE IF EXISTS {dst_schema}.{dst_tbl} CASCADE;'), pg_conn_param)
  faibDataManagement::sendSQLstatement(glue('CREATE TABLE {dst_schema}.{dst_tbl} AS {sqlstmt};'), pg_conn_param)
  ## add harded coded fid primary key sequenctial integer
  faibDataManagement::sendSQLstatement(glue("ALTER TABLE {dst_schema}.{dst_tbl} ADD COLUMN {pk} int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;"), pg_conn_param)
  faibDataManagement::sendSQLstatement(tbl_comment, pg_conn_param)
  faibDataManagement::sendSQLstatement(glue("ANALYZE {dst_schema}.{dst_tbl};"), pg_conn_param)
  }
