#' Create a PG non spatial table from Foreign data wrapper table
#'
#' @param foreignTable coming soon
#' @param outTblName coming soon
#' @param pk coming soon
#' @param schema coming soon
#' @param connList coming soon
#' @param attr2keep optional
#'
#' @return None
#' @export
#'
#' @examples coming soon


fdwTbl2PGnoSpatial <- function(foreignTable, outTblName, pk, outSchema, connList, fdwSchema = 'load', attr2keep = NULL, where = '', table_comment) {

  if (grepl("\\.", foreignTable)) {
    oraTblNameNoSchema <- unlist(strsplit(foreignTable, split = "[.]"))[-1]
  } else {
    oraTblNameNoSchema <- foreignTable
  }

  geomName <- faibDataManagement::getGeomNamePG(fdwSchema, oraTblNameNoSchema, connList)
  outNameSchema <- glue("{outSchema}.{outTblName}")
  if(where == '' || is.null(where) || is.na(where)) {
    where <- ''
  } else {
    where <- gsub("\'","\'\'", where)
    where <- glue("where {where}")
  }

  if(is.null(attr2keep) || attr2keep == '' || is.na(attr2keep)) {
    ## Keep all attributes
    query = glue("SELECT
                    'SELECT ' || array_to_string(
                                                  ARRAY(
                                                      SELECT
                                                        'o' || '.' || c.column_name
                                                      FROM
                                                        information_schema.columns As c
                                                      WHERE
                                                        table_name = '{oraTblNameNoSchema}'
                                                      AND
                                                        table_schema = 'load'
                                                      AND
                                                        c.column_name NOT IN ('{geomName}')
                                                    )
                                      , ',') || '
                 FROM
                  {fdwSchema}.{oraTblNameNoSchema} AS o {where} ' As sqlstmt")

    sqlstmt <- (faibDataManagement::getTableQueryPG(query, connList))$sqlstmt
  } else {
    # Split the original string into elements
    elements <- strsplit(attr2keep, ",")[[1]]

    # Add single quotes around each element
    quoted_elements <- paste0("'", elements, "'")

    # Join the quoted elements into a new string
    attr2keep <- paste(quoted_elements, collapse = ',')

    query = glue("SELECT
                    'SELECT ' || array_to_string(
                                                  ARRAY(
                                                      SELECT
                                                        'o' || '.' || c.column_name
                                                      FROM
                                                        information_schema.columns As c
                                                      WHERE
                                                        table_name = '{oraTblNameNoSchema}'
                                                      AND
                                                        table_schema = 'load'
                                                      AND
                                                        c.column_name NOT IN ('{geomName}')
                                                      AND
                                                        c.column_name IN ({attr2keep})
                                                    )
                                      , ',') || '
                 FROM
                  {fdwSchema}.{oraTblNameNoSchema} AS o {where} ' As sqlstmt")
    sqlstmt <- (faibDataManagement::getTableQueryPG(query, connList))$sqlstmt
  }
  today_date <- format(Sys.Date(), "%Y-%m-%d")
  ## Alter the SQL statement to cast the
  faibDataManagement::sendSQLstatement(glue('DROP TABLE IF EXISTS {outSchema}.{outTblName} CASCADE;'),connList)
  faibDataManagement::sendSQLstatement(glue('CREATE TABLE {outSchema}.{outTblName} AS {sqlstmt};'),connList)
  ## alter the pk type to integer
  faibDataManagement::sendSQLstatement(glue("ALTER TABLE {outSchema}.{outTblName} ADD COLUMN fid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;"), connList)
  faibDataManagement::sendSQLstatement(table_comment, connList)
  faibDataManagement::sendSQLstatement(glue("ANALYZE {outSchema}.{outTblName};"),connList)
  }
